### ISSUE TITLE
메인페이지 todo 개발

### ISSUE THREAD

**Issue by kkwang1223** [92-crew/dod-web#28]
- [x] 사이드바 데이터 바인딩
- [x] 메인 컨텐츠 데이터 바인딩
- [x] api 서버 연동
- [x] 사이드바 이벤트 바인딩
- [x] 메인 컨텐츠 이벤트 바인딩
